name: Dev Workflow - Test and check thing

on:
  push:
    branches-ignore:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Tests
        run: ./gradlew test

      - name : Build Project
        run: |
          ./gradlew assembleMuseumENDebug
          ./gradlew assembleMuseumNLDebug