name: Dev Workflow - Test and check thing

on:
  push:
    branches:
      - implement-cicd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Decode Keystore
        id: decode_keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/sign.jks

          echo ${TMP_KEYSTORE_FILE_PATH}
      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Access API_KEY
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          echo > ./local.properties
          echo API_KEY=\"$API_KEY\" > ./local.properties

      - name: Read local.properties
        id: getlocal
        run: echo "::set-output name=localpro::$(cat ./local.properties)"

      - name: Access SIGNING_INFO
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        run: |
          echo >> ./gradle.properties
          echo SIGNING_STORE_PASSWORD=\"$SIGNING_STORE_PASSWORD\" >> ./gradle.properties
          echo SIGNING_KEY_ALIAS=\"$SIGNING_KEY_ALIAS\" >> ./gradle.properties
          echo SIGNING_KEY_PASSWORD=\"$SIGNING_KEY_PASSWORD\" >> ./gradle.properties

          echo ${SIGNING_STORE_PASSWORD}
          echo ${SIGNING_KEY_ALIAS}
          echo ${SIGNING_KEY_PASSWORD}

      - name: Read gradle.properties
        id: getgradle
        run: echo "::set-output name=gradle::$(cat ./gradle.properties)"

      #      - name: Run Tests
      #        run: ./gradlew test

#      - name: Assemble Release Bundle
#        run: |
#          ./gradlew assembleRelease
#
#      - uses: r0adkll/sign-android-release@v1
#        name: Sign app APK
#        # ID used to access action output
#        id: sign_app
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.KEYSTORE }}
#          alias: ${{ secrets.SIGNING_KEY_ALIAS }}
#          keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
#        env:
#          # override default build-tools version (29.0.3) -- optional
#          BUILD_TOOLS_VERSION: "30.0.2"
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: Signed app bundle
#          path: ${{steps.sign_app.outputs.signedReleaseFile}}